### ISSUE TITLE
pCO2 calcs

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/paper-gigas-early-gametogenic-exposure#1]
I took a stab at calculating pCO2 using the `seacarb` program and TA / pH values in the paper, as well as T and S from the [grab sample](https://github.com/RobertsLab/paper-gigas-early-gametogenic-exposure/tree/master/data/Water-Chemistry-Data/2018-04-30-pH-Calculations/2018-04-30-Grab-Samples) files.  Resulting pCO2 values are pretty darn high compared to what many others use in OA experiments, particularly for the ambient group - [see script](https://raw.githubusercontent.com/laurahspencer/O.lurida_Stress/master/Test-Seacarb-Script.R); results are in comments in the script but also here for days 5, 33, 48:  

pCO2 (uatm) for ambient tanks: 748, 919, 866  
pCO2 (uatm) for low pH tanks: 2469, 3267, 3320

**Comment by kubu4** [comment]
This is an interesting observation.

One thing that hasn't been addressed in this whole TA calculation stuff is potentially applying an "offset" to our calculated TA.

What I mean by this is that when doing the titrations, we also perform a titration on a known reference standard. One can then determine the difference in TA between our measurement of the standard and what TA the reference standard is supposed to be. This ratio/difference can then be applied to actual sample measurements.

Our measurements of the reference standard have consistently yielded TA values ~20% higher than what the certification indicates. It's possible that this could be one explanation for the comparatively high levels of pCO<sub>2</sub> seen in these samples.

However, here's a catch. Having spoken with Hollie about this difference, she indicated that a researcher could handle it in one of two ways:

1. Calculate offset value and apply to measured samples.

2. Report measured TA values and the certified TA value for the reference standard and leave it at that.

Regardless, I have the reference standard data, but have not taken the time to do anything with it as of yet. Sorry! When I passed the TA data on to @yaaminiv, there wasn't mention of using the data for anything other than deciding on whether or not to process additional samples within the set. As such, finishing the R script to pull reference standard TA measurements was low priority.

**Comment by laurahspencer** [comment]
The pCO2 values are not necessarily wrong, give ambient pH was 7.8, but
this is good to know for this and future papers using TA.
(I know that many OA studies use pCO2 in the ~400uatm for ambient.)
